name:  WebApp (Blazor Server)

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      prod_release:
        description: 'Do you want to release to production?'
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          include-prerelease: false

      - name: Build with dotnet
        run: dotnet build ./BlazorExpress.Bulma.Demo.Server/BlazorExpress.Bulma.Demo.Server.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish ./BlazorExpress.Bulma.Demo.Server/BlazorExpress.Bulma.Demo.Server.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    if: ${{ inputs.prod_release }} 
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE30BC18ACB8455EA02CF2B3AE4234A4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B00A222B2DC94C8AA6B8C1AC64A5DA9B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21D06FCB7150414C8389095C3815CA30 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bulma-blazorexpress'
          slot-name: 'Production'
          package: .
          
